{% set name = "arbol" %}
{% set version = "2021.5.27.641" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arbol-{{ version }}.tar.gz
  sha256: 5b944a29bbbe488f71251a2cd247bb3eacfdc1e927350e7f9cd9de797b5d1f70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - arbol
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/royerlab/arbol
  summary: arbol -- Arborescent Printouts in Python
  license: BSD-3-Clause OR MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
